# Generated by Django 5.0.6 on 2024-06-01 07:51

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_skill_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='Название компании')),
                ('vacancy_name', models.CharField(max_length=50, verbose_name='Название должности')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_start', main.models.MonthDateField(verbose_name='Дата начала')),
                ('date_finish', main.models.MonthDateField(blank=True, null=True, verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience',
            },
        ),
        migrations.CreateModel(
            name='ExperienceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('stack', models.CharField(max_length=50, verbose_name='Стэк')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.experience', verbose_name='Опыт работы')),
            ],
            options={
                'verbose_name': 'Experience project',
                'verbose_name_plural': 'Experience projects',
            },
        ),
    ]
